package com.seal.seal_backend.common.audit;

/** Actions that MUST be audit-logged (BR-AUD-02). Use as action_type in AuditLog. */
public enum AuditAction {
    EVALUATION_STARTED,
    EVALUATION_UPDATED,
    EVALUATION_SUBMITTED,
    SCORE_CREATED, SCORE_UPDATED,
    ROUND_LOCKED, ROUND_UNLOCKED,
    TEAM_APPROVED, TEAM_REJECTED,
    TEAM_DISQUALIFIED, TEAM_REINSTATED,
    ACCOUNT_APPROVED, ACCOUNT_REJECTED, ACCOUNT_REACTIVATED,
    RESULT_PUBLISHED,
    EVENT_SUBMITTED, EVENT_APPROVED, EVENT_REJECTED,
    EVENT_OPENED, EVENT_STARTED, EVENT_COMPLETED, EVENT_ARCHIVED,
    BUDGET_APPROVED, BUDGET_REAPPROVAL_TRIGGERED,
    DISCIPLINE_OR_QUOTA_CHANGED,
    STAFF_ACCOUNT_CREATED, STAFF_ACCOUNT_DEACTIVATED,
    ROLE_ASSIGNED, ROLE_REVOKED,
    SYSTEM_CONFIG_CHANGED
}
